apiVersion: v1
kind: ImageStream
metadata:
  annotations:
  creationTimestamp: null
  generation: 7
  name: mysql
spec:
  tags:
  - annotations:
      description: Provides a MySQL database on CentOS 7. For more information about using this database image see http://docs.thedigitalgarage.io/using_images/db_images/mysql.html.
      iconClass: icon-mysql-database
      tags: mysql,db
      version: "5.5"
    from:
      kind: DockerImage
      name: thedigitalgarage/mysql-55-centos7:latest
    name: "5.5"
  - annotations:
      description: Provides a MySQL database on CentOS 7. For more information about using this database image see http://docs.thedigitalgarage.io/using_images/db_images/mysql.html.
      iconClass: icon-mysql-database
      tags: mysql,db
      version: "5.6"
    from:
      kind: DockerImage
      name: thedigitalgarage/mysql-56-centos7:latest
    name: "5.6"
